kind: Namespace
apiVersion: v1
metadata:
  name: wireguard
  labels:
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/instance: wireguard
---
kind: Service
apiVersion: v1
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/instance: wireguard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 51820
    protocol: UDP
  selector:
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/instance: wireguard
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: wireguard
  namespace: wireguard
  labels:
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/instance: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wireguard
      app.kubernetes.io/instance: wireguard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wireguard
        app.kubernetes.io/instance: wireguard
    spec:
      containers:
      - name: wireguard
        image: docker.io/angoll/wireguard:latest
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true
        volumeMounts:
          - name: configuration
            mountPath: /etc/wireguard.conf
            subPath: wireguard.conf
            readOnly: true
          - name: kernel-modules
            mountPath: /lib/modules
            readOnly: true
        ports:
        - containerPort: 51820
          protocol: UDP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
        - name: configuration
          configMap:
            name: wireguard-config
        - name: kernel-modules
          hostPath:
            path: /lib/modules
            type: Directory
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - wireguard
            topologyKey: "kubernetes.io/hostname"
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 5
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 5
---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/instance: wireguard
  name: wireguard-config
  namespace: wireguard
data:
  wireguard.conf: |
    [Interface]
    PrivateKey = <privateIP>
    # Address = 10.254.0.1/24   # Set at the entrypoint

    [Peer]
    PublicKey = <Client1_publicKey>
    # PresharedKey = <Client1_preshared>  # Optional
    AllowedIPs = 10.254.0.2/32 # Wireguard Client IP
    PersistentKeepalive = 25

    [Peer]
    PublicKey = <Client2_publicKey>
    # PresharedKey = <Client2_preshared>  # Optional
    AllowedIPs = 10.254.0.3/32  # Wireguard Client IP
    PersistentKeepalive = 20
